SmartGarage/SmartGarage.Web/Models/MessagePartial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Models
{
    public class MessagePartial
    {
        public string Message { get; set; }
        public bool GoodOrBad { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Controllers/VisitController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Data.Models;
using SmartGarage.Data.Models.Enums;
using SmartGarage.Services.Models;
using SmartGarage.Services.Models.CreateDTOs;
using SmartGarage.Services.Models.UpdateDTOs;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("[controller]")]
    public class VisitController : Controller
    {
        private readonly IVehicleModelService vehicleModelService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVisitService visitService;
        private readonly IVehicleService vehicleService;
        private readonly ISvcService svcService;
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;

        public VisitController(IVisitService visitService,
            IVehicleService vehicleService,
            IVehicleModelService vehicleModelService,
            IManufacturerService manufacturerService,
            UserManager<User> userManager, ISvcService svcService,
            IUserService userService)
        {
            this.vehicleModelService = vehicleModelService;
            this.manufacturerService = manufacturerService;
            this.visitService = visitService;
            this.vehicleService = vehicleService;
            this.userManager = userManager;
            this.svcService = svcService;
            this.userService = userService;
        }

        [Authorize()]
        [HttpGet]
        public async Task<IActionResult> Index(string isChecked, int pageNumber = 1, string currency = "EUR")
        {
            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            if (User.IsInRole("Employee"))
            {
                return View(await visitService.GetAllAsync(new FilterVisitQuery(), pagerQueryObj, currency, isChecked));
            }

            return View(await visitService
                .GetAllAsync(new FilterVisitQuery(), pagerQueryObj, currency, isChecked, int.Parse(userManager.GetUserId(User))));
        }

        [Authorize()]
        [HttpGet("Details")]
        public async Task<IActionResult> Details(int id, int currencyChange)
        {
            var cur = (Currencies)currencyChange;
            var visit = await visitService.GetAsync(id, cur.ToString());

            visit.Currency = cur.ToString();

            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        [Authorize()]
        [HttpGet("ExchangeCurrency")]
        public async Task<IActionResult> ExchangeCurrency(int id, string currencyChange)
        {
            var visit = await visitService.GetAsync(id, currencyChange);

            visit.Currency = currencyChange;

            return PartialView("_VisitDetailsPartial", visit);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Create")]
        public async Task<IActionResult> Create()
        {
            var model = new CreateVisitNotRegisterdCustomer()
            {
                Manufacturers = await manufacturerService.GetAllAync(),
                Models = await vehicleModelService.GetAllAsync(),
                Services = svcService.GetAllAsync().Result.ToList()
            };
            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Create")]
        public async Task<IActionResult> Create(CreateVisitNotRegisterdCustomer model)
        {
            var customer = new CreateUserDTO()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Phone = model.Phone
            };
            bool customerResult;
            try
            {
                customerResult = await userService.CreateCustomerAsync(customer);
            }
            catch
            {
                TempData["Messages"] = "User already exist";
                model.Manufacturers = await manufacturerService.GetAllAync();
                model.Models = await vehicleModelService.GetAllAsync();
                model.Services = svcService.GetAllAsync().Result.ToList();
                return View(model);
            }

            if (customerResult)
            {
                var newCustomer = await userManager.FindByEmailAsync(model.Email);
                try
                {
                    int modelId;
                    int makeId;
                    var modelResult = int.TryParse(model.VehicleModelId, out modelId);
                    var makeResult = int.TryParse(model.ManufacturerId, out makeId);

                    if (!makeResult)
                    {
                        var make = await manufacturerService.GetAync(model.ManufacturerId);
                        makeId = make.Id;
                    }

                    if (!modelResult)
                    {
                        var vehicleModel = await vehicleModelService.GetAsync(model.VehicleModelId);
                        modelId = vehicleModel.Id;
                    }


                    var vehicle = new CreateVehicleDTO()
                    {
                        ModelId = modelId,
                        ManufacturerId = makeId,
                        IdentityNumber = model.IdentityNumber,
                        PlateNumber = model.PlateNumber,
                        Type = model.Type,
                        CustomerId = newCustomer.Id

                    };

                    var vehicleResult = await vehicleService.CreateAsync(vehicle);

                    if (vehicleResult)
                    {
                        var visit = new CreateVisitDTO()
                        {
                            VehicleId = newCustomer.Vehicles.FirstOrDefault().Id
                        };
                        var servicesToAdd = model.Services.Where(x => x.AddToVisit).Select(x => x.Id);
                        var visitResult = await visitService.Create(visit);
                        if (visitResult != 0)
                        {
                            foreach (var item in servicesToAdd)
                            {
                                await visitService.AddServiceToVisit(visitResult, item);
                                continue;
                            }
                        }
                            TempData["Messages"] = "Successfully created visit";
                            return RedirectToAction(nameof(Index));
                    }

                }
                catch
                {
                    await userService.DeleteForRealAsync(newCustomer.Id);
                    TempData["Messages"] = "You need to choose model and make";
                    model.Manufacturers = await manufacturerService.GetAllAync();
                    model.Models = await vehicleModelService.GetAllAsync();
                    model.Services = svcService.GetAllAsync().Result.ToList();
                    return View(model);
                }
            }
            TempData["Messages"] = "There was a problem";
            return View();
        }



        [Authorize(Roles = "Employee")]
        [HttpGet("AddVisitToCustomer/{id}")]
        public async Task<IActionResult> AddVisitToCustomer(int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            var mode = new AddVisitToCustomerViewModel()
            {
                CustomerName = customer.Name,
                Vehicles = customer.Vehicles.ToList(),
                Services = svcService.GetAllAsync().Result.ToList()
            };
            return View(mode);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("AddVisitToCustomer/{id}")]
        public async Task<IActionResult> AddVisitToCustomer(AddVisitToCustomerViewModel model, int id)
        {
            var newVisit = new CreateVisitDTO()
            {
                VehicleId = model.VehicleId
            };

            
            var visitTOcheck = await visitService.GetAllAsync();
            var result = visitTOcheck.Where(x => x.VehicleId == model.VehicleId).Any(x=>x.DateOut == "No out date assigned yet");
            if (result)
            {
                var customer = await userService.GetCustomerAsync(id);
                model.CustomerName = customer.Name;
                model.Vehicles = userService.GetCustomerAsync(id).Result.Vehicles.ToList();
                model.Services = svcService.GetAllAsync().Result.ToList();

                TempData["Messages"] = "Vehicle is in the shop already";
                return View(model);
            }
            var visitId = await visitService.Create(newVisit);
            var servicesToAdd = model.Services.Where(x => x.AddToVisit).Select(x => x.Id);

            if (visitId != 0)
            {
                foreach (var item in servicesToAdd)
                {
                    await visitService.AddServiceToVisit(visitId, item);
                    continue;
                }
            }
            TempData["Messages"] = "Successfully added visit";
            return RedirectToAction("Index", "Customers");
        }


        [Authorize(Roles = "Employee")]
        [HttpGet("EditServices/{id}")]
        public async Task<IActionResult> EditServices(int id)
        {
            var visit = await visitService.GetAsync(id);

            var model = new EditServicesInVisitViewModel
            {
                Services = visit.Services.ToList(),

SmartGarage/SmartGarage.Web/Views/Shared/_CreatePopUpModel.cshtml
@model SmartGarage.Services.Models.VehicleModelDTO
@using SmartGarage.Web.Models
@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<div class="container mt-3">
    <h1>Create</h1>

    <h4>Model</h4>
    <hr />
    <div id="messgePartialModel">
        <partial name="_MessagePartial" model="new MessagePartial()" />
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Model</label>
                <input id="Modelname" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="createModelButton" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

SmartGarage/SmartGarage.Web/Views/Shared/_CreatePopUpPartial.cshtml
@model SmartGarage.Services.Models.ManufacturerDTO
@using SmartGarage.Web.Models
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery AntiForgery
@{
    ViewData["Title"] = "CreatePopUp";
    Layout = null;
}
<div class="container mt-3">
    <h1>Create</h1>

    <h4>Manufacturer</h4>
    <hr />
    <div id="messgePartial">
        <partial name="_MessagePartial" model="new MessagePartial()"/>
    </div>
    <div class="row">
        <div class="col-12">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Manufacturer</label>
                    <input id="name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input id="createButton" type="submit" value="Create" class="btn btn-primary" />
                </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.Web/Views/Shared/_CustomersPartialViewPager.cshtml
@model SmartGarage.Services.Helpers.Pager<UserDTO>
@using SmartGarage.Services.Models;

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Phone
            </th>
            <th>
                Email
            </th>
            <th>
                Last visit
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(i => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(i => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(i => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(i => item.LastVisit)
                </td>
                <td>
                    <a asp-controller="Vehicles" asp-action="Create" asp-route-id="@item.Id" class="btn btn-outline-success" title="Add Vehicle"><i class="fas fa-car"></i></a>
                    <a asp-controller="Visit" asp-action="AddVisitToCustomer" asp-route-id="@item.Id" class="btn btn-outline-success" title="Add Visit"><i class="fas fa-warehouse"></i></a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Edit"><i class="far fa-edit"></i></a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info" title="Details"><i class="fas fa-info-circle"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Delete"><i class="far fa-trash-alt"></i></a>

                </td>
            </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.PrevPage ? "disabled" : "";
    var nextDisabled = !Model.NextPage ? "disabled" : "";
}

<a href="#" id="prev" class="btn btn-default @prevDisabled">
    Previous
</a>
@if (Model.TotalPages == 0)
{
    <a>No results</a>
}
else
{
    <a> @Model.Page / @Model.TotalPages</a>
}

<a href="#" id="next" class="btn btn-default @nextDisabled">
    Next
</a>

<input id="pageNum" hidden value="@Model.Page" />

SmartGarage/SmartGarage.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SmartGarage.Data.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartGarage.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark box-shadow">
            <div class="container">
                <a asp-controller="Home" asp-action="Index"><img src="https://i.ibb.co/8z8DdNJ/Smart-Garage-Official-Logo-White.png" alt="Smart-Garage-Official-Logo" border="0"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-center">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Visit" asp-action="Index">Visits</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                            </li>
                            @if (User.IsInRole("Employee"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2021 - SmartGarage.Web - <a class="text-light ml-2" asp-area="" asp-controller="Home" asp-action="Privacy"><ins>Privacy</ins></a>
            @if (User.IsInRole("Employee"))
            {
                <a class="text-light ml-2" asp-area="" asp-controller="Manufacturers" asp-action="Index"><ins>Manufacturers</ins></a>
            }
            <a class="text-light ml-2" asp-area="" asp-controller="Home" asp-action="ContactUs"><ins>Contact Us</ins></a>
            <a class="text-light ml-2" asp-area="" asp-controller="Home" asp-action="Location"><ins>Location</ins></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/pdfJs.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartGarage/SmartGarage.Web/Views/Shared/_MessagePartial.cshtml
@model SmartGarage.Web.Models.MessagePartial
@{
    Layout = null;
}
<div class="text-center">
    @{
        if (Model.Message == null)
        {

        }
        else if (Model.GoodOrBad)
        {
            <div class="alert alert-success" role="alert">
                <p>@Model.Message</p>
            </div>

        }
        else
        {
            <div class="alert alert-danger" role="alert">
                <p>@Model.Message</p>
            </div>
        }
    }
</div>

SmartGarage/SmartGarage.Web/Views/Shared/_PartialViewServicesPager.cshtml
@model SmartGarage.Services.Helpers.Pager<ServiceDTO>
@using SmartGarage.Services.Models;
@{
    Layout = null;
}

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                @if (User.IsInRole("Employee"))
                {
                    <a asp-action="Create" class="btn-sm btn-success" title="Create new"><i class="far fa-plus-square"></i></a>
                }
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(i => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(i => item.Price)
                </td>
                <td>


                    @if (User.IsInRole("Employee"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="far fa-edit"></i></a>
                    }

                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info"> <i class="fas fa-info-circle"></i></a>

                    @if (User.IsInRole("Employee"))
                    {
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger"><i class="far fa-trash-alt"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.PrevPage ? "disabled" : "";
    var nextDisabled = !Model.NextPage ? "disabled" : "";
}
<a id="prev" href="#" class="btn btn-default @prevDisabled">
    Previous
</a>
@if (Model.TotalPages == 0)
{
    <a>No results</a>
}
else
{
    <a> @Model.Page / @Model.TotalPages</a>
}
<a id="next" href="#" class="btn btn-default @nextDisabled">
    Next
</a>
<input value="@Model.Page" hidden id="pageNumber" />

SmartGarage/SmartGarage.Web/Views/Shared/_PartialViewVisitPager.cshtml
@model SmartGarage.Services.Helpers.Pager<VisitDTO>
@using SmartGarage.Services.Models;

<style>
    th:hover {
        cursor: pointer;
    }
</style>

<div class="container-all">
    @{
        <table class="table table-striped">
            <thead>
                <tr>
                    @if (User.IsInRole("Employee"))
                    {
                        <th onclick="sortTable(0)">Customer</th>
                    }
                    <th onclick="sortTable(1)">Vehicle</th>
                    <th onclick="sortTable(2)">Date</th>
                    <th onclick="sortTable(3)">Status</th>

                    <th>
                        @if (User.IsInRole("Employee"))
                        {
                            <a asp-action="Create" class="btn-sm btn-success" title="Create new"><i class="far fa-plus-square"></i></a>
                        }

                    </th>
                </tr>
            </thead>
            <tbody id="myTableBody">
                @foreach (var item in Model.Items)
                {
                    <tr>
                        @if (User.IsInRole("Employee"))
                        {
                            <td>

                                @Html.DisplayFor(i => item.CustomerName)

                            </td>
                        }
                        <td title="Plate number: @item.PlateNumber">
                            @Html.DisplayFor(i => item.VehicleMake) @Html.DisplayFor(i => item.VehicleModel)
                        </td>

                        <td>
                            @Html.DisplayFor(i => item.DateIn) - @Html.DisplayFor(i => item.DateOut)
                        </td>
                        <td>
                            @Html.DisplayFor(i => item.StatusName)
                        </td>

                        <td>
                            @if (User.IsInRole("Employee"))
                            {
                                if (item.DateOut == "No out date assigned yet")
                                {
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Edit"><i class="far fa-edit"></i></a>
                                }
                                else
                                {
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary disabled" title="Edit"><i class="far fa-edit"></i></a>
                                }
                            }
                            @if (User.IsInRole("Employee"))
                                if (item.DateOut == "No out date assigned yet")
                                {
                                    <a asp-action="EditServices" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Edit services in visit"><i class="fas fa-tools"></i></a>
                                }
                                else
                                {
                                    <a asp-action="EditServices" asp-route-id="@item.Id" class="btn btn-outline-primary disabled" title="Edit services in visit"><i class="fas fa-tools"></i></a>
                                }
                            @if (User.IsInRole("Employee"))
                            {
                                if (item.Status != 0 ^ item.DateOut != "No out date assigned yet")
                                {
                                    <a asp-action="CheckOut" asp-route-id="@item.Id" class="btn btn-outline-warning disabled" title="CheckOut"><i class="fas fa-door-open"></i></a>
                                }
                                else
                                {
                                    <a asp-action="CheckOut" asp-route-id="@item.Id" class="btn btn-outline-warning" title="CheckOut"><i class="fas fa-door-open"></i></a>
                                }

                            }
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info" title="Details"><i class="fas fa-info-circle"></i></a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
@{
    var prevDisabled = !Model.PrevPage ? "disabled" : "";
    var nextDisabled = !Model.NextPage ? "disabled" : "";
}
<a id="prev" href="#" class="btn btn-default @prevDisabled">
    Previous
</a>
@if (Model.TotalPages == 0)
{
    <a>No results</a>
}
else
{
    <a> @Model.Page / @Model.TotalPages</a>
}

<a id="next" href="#" class="btn btn-default @nextDisabled">
    Next
</a>
<input value="@Model.Page" hidden id="pageNum" />


@section Scripts {
    <script src="~/js/SortTable.js"></script>
}

SmartGarage/SmartGarage.Web/Views/Shared/_VisitDetailsPartial.cshtml
@model SmartGarage.Services.Models.VisitDTO

@{
    Layout = null;
}

<table class="table w-50">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Action               
            </th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody style="height: 150px;overflow: scroll;">
        @foreach (var item in Model.Services)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    <a asp-controller="Service" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    @item.Price @Model.Currency
                </td>

            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td class="font-weight-bold"> @Html.DisplayNameFor(model => model.TotalPrice)</td>
            <td></td>
            <td> @Html.DisplayFor(model => model.TotalPrice)  @Model.Currency</td>
        </tr>
    </tfoot>
</table>