SmartGarage/SmartGarage.Web/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using SmartGarage.Data.Models;
using SmartGarage.Services.Helpers;
using SmartGarage.Services.ModelMapper;
using SmartGarage.Services.Models;
using SmartGarage.Services.Models.CreateDTOs;
using SmartGarage.Services.Models.UpdateDTOs;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [Route("[controller]")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class CustomersController : Controller
    {
        private readonly IVehicleService vehicleService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleModelService vehicleModelService;
        private readonly IUserService userService;
        private readonly IModelMapper modelMapper;
        private readonly IVisitService visitService;
        private readonly UserManager<User> userManager;

        public CustomersController(IVehicleService vehicleService, IManufacturerService manufacturerService,
            IVehicleModelService vehicleModelService, IModelMapper modelMapper,
            IUserService userService, IVisitService visitService, UserManager<User> userManager)
        {
            this.vehicleService = vehicleService;
            this.manufacturerService = manufacturerService;
            this.vehicleModelService = vehicleModelService;
            this.modelMapper = modelMapper;
            this.userService = userService;
            this.visitService = visitService;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var pagerQueryObj = new PagerQueryObject(1, 0);

            var filterCustomers = new FilterUserQuery();

            var customers = await userService.GetAllCustomersAsync(filterCustomers, pagerQueryObj);

            return View(customers);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Details")]
        public async Task<IActionResult> Details(int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }
        [Authorize(Roles = "Employee")]
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await userService.GetCustomerAsync(id);

            var model = new CustomerViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email
            };

            if (user == null)
            {
                return NotFound();
            }

            return View(model);
        }
        [Authorize(Roles = "Employee")]
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await userService.DeleteAsync(id);

            if (result)
            {
                TempData["Messages"] = "Successfully deleted";
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await userService.GetCustomerAsync(id);
            var model = new CustomerViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Phone = user.Phone,
            };

            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Edit/{id}")]
        public async Task<IActionResult> Edit([Bind("FirstName,LastName,Email,Phone")] CustomerViewModel model, int id)
        {
            var userToUpdate = new UpdateUserDTO()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Phone = model.Phone,
            };

            var result = await userService.UpdateAsync(userToUpdate, id);
            if (result)
            {
                TempData["Messages"] = "Successfully updated";
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("PartialPager")]
        public async Task<IActionResult> PartialPager(string customerName, string email, string phone, string vehicle,
            DateTime from, DateTime to,string order,bool dateFilter,string filterBy, int pageNumber = 1)
        {

            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            var filterCustomers = new FilterUserQuery()
            {
                Name = customerName,
                Email = email,
                Phone = phone,
                Vehicle = vehicle,
                From = from,
                To = to,
                Order = order,
                DateFilter = dateFilter,
                SortBy = filterBy
                
            };

            var customers = await userService.GetAllCustomersAsync(filterCustomers, pagerQueryObj);

            return PartialView("_CustomersPartialViewPager",customers);
        }

        [HttpGet("ChangePassword/{id}")]
        public async Task<IActionResult> ChangePassword (int id)
        {
            var customer = await userService.GetUserAsync(id);

            return View(customer);
        }
        [HttpPost("ChangePassword/{id}")]
        public async Task<IActionResult> ChangePassword(int id,string password)
        {
            var result = await userService.ResetPassword(password,id);
            if (result)
            {
                TempData["Messages"] = "Successfully changed password";
            }
            else
            {
                TempData["Messages"] = "Invalid password";
            }
            var customer = await userService.GetUserAsync(id);
            return View(customer);
        }

        [HttpPost("SendResetPassowrd")]
        public async Task<IActionResult> SendResetPassowrd(string email)
        {
            var user = await userManager.FindByEmailAsync(email);
            if (email!=null)
            {
                var code = await userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                SendEmail.SendPassword(
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",email);
                TempData["Messages"] = "Successfully send link to email";
               return RedirectToAction("Details", new { id = user.Id });
            }
            TempData["Messages"] = "Something went wrong";
            return RedirectToAction("Details", new { id = user.Id });
        }

        [HttpGet("SendPdf/{id}")]
        public async Task<IActionResult> SendPdf(int id)
        {
            var visits = await visitService.GetAllAsync(id);
            return View(visits.ToList());
            
        }

        [HttpPost("SendPdf/{id}")]
        public async Task<IActionResult> SendPdf(List<VisitDTO> comingVisits,int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            var visits = await visitService.GetAllAsync(id);
            var visitsToSend = comingVisits.Where(x => x.ToSend).Select(x => x.Id);
            await SendEmail.SendPdfAsync(visits.Where(x=> visitsToSend.Contains(x.Id)).ToList(),customer.Email);

            TempData["Messages"] = "Email sended";
            return RedirectToAction("Details", new { id = customer.Id });

        }
    }
}

SmartGarage/SmartGarage.Web/Controllers/VehiclesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.Data.Models;
using SmartGarage.Services.ModelMapper;
using SmartGarage.Services.Models.CreateDTOs;
using SmartGarage.Services.Models.UpdateDTOs;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("[controller]")]
    public class VehiclesController : Controller
    {
        private readonly IVehicleService vehicleService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleModelService vehicleModelService;
        private readonly IUserService userService;
        private readonly IModelMapper modelMapper;
        private readonly UserManager<User> userManager;

        public VehiclesController(IVehicleService vehicleService, IManufacturerService manufacturerService,
            IVehicleModelService vehicleModelService, IModelMapper modelMapper, IUserService userService,
            UserManager<User> userManager)
        {
            this.vehicleService = vehicleService;
            this.manufacturerService = manufacturerService;
            this.vehicleModelService = vehicleModelService;
            this.modelMapper = modelMapper;
            this.userService = userService;
            this.userManager = userManager;
        }

        [Authorize()]
        [HttpGet]
        public async Task<IActionResult> Index(string searchString, int pageNumber = 1)
        {
            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            if (User.IsInRole("Employee"))
            {
                return View(await vehicleService.GetAllAsync(searchString, pagerQueryObj));
            }
            return View(await vehicleService
                .GetAllAsync(searchString, pagerQueryObj, int.Parse(userManager.GetUserId(User))));
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Create/{id}")]
        public async Task<IActionResult> Create(int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            var model = new VehicleViewModel
            {
                Manufacturers = await manufacturerService.GetAllAync(),
                Models = await vehicleModelService.GetAllAsync(),
                CustomerName = customer.Name,
                CustomerId = id.ToString()
                
            };

            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Create/{id}")]
        public async Task<IActionResult> Create(VehicleViewModel model, int id)
        {
            
            try
            {
                int modelId;
                int makeId;
                var modelResult = int.TryParse(model.VehicleModelId, out modelId);
                var makeResult = int.TryParse(model.ManufacturerId, out makeId);

                if (!makeResult)
                {
                    var make = await manufacturerService.GetAync(model.ManufacturerId);
                    makeId = make.Id;
                }

                if (!modelResult)
                {
                    var vehicleModel = await vehicleModelService.GetAsync(model.VehicleModelId);
                    modelId = vehicleModel.Id;
                }

                var vehicle = new CreateVehicleDTO()
                {
                    CustomerId = id,
                    PlateNumber = model.PlateNumber,
                    IdentityNumber = model.IdentityNumber,
                    ManufacturerId = makeId,
                    ModelId = modelId,
                    Type = int.Parse(model.Type)
                };
                if (ModelState.IsValid)
                {
                    await vehicleService.CreateAsync(vehicle);
                    TempData["Messages"] = "Successfully created vehicle";
                    return RedirectToAction("Index", "Customers");
                }
                return View(model);
            }
            catch
            {
                model.CustomerName = userService.GetCustomerAsync(id).Result.Name;
                model.Manufacturers = await manufacturerService.GetAllAync();
                model.Models = await vehicleModelService.GetAllAsync();
                TempData["Messages"] = "Need to chose make and model";
                return View(model);
            }
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var vehicle = await vehicleService.GetAsync(id);
            var model = new VehicleViewModel
            {
                CustomerId = vehicle.CustomerId.ToString(),
                IdentityNumber = vehicle.IdentityNumber,
                PlateNumber = vehicle.PlateNumber,
                ManufacturerId = vehicle.ManufacturerId.ToString(),
                VehicleModelId = vehicle.ModelId.ToString(),
                Manufacturers = await manufacturerService.GetAllAync(),
                Models = await vehicleModelService.GetAllAsync(),
                CustomerName = vehicle.CustomerFullName,
                Customers = await userService.GetAllCustomersAsync()
            };

            return View(model);

        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Edit/{id}")]
        public async Task<IActionResult> Edit(VehicleViewModel model, int id)
        {
            var vehicleToUpdate = new UpdateVehicleDTO()
            {
                IdentityNumber = model.IdentityNumber,
                PlateNumber = model.PlateNumber,
                CustomerId = int.Parse(model.CustomerId),
                ManufacturerId = int.Parse(model.ManufacturerId),
                ModelId = int.Parse(model.VehicleModelId),
                Type = int.Parse(model.Type)
            };

            var result = await vehicleService.UpdateAsync(vehicleToUpdate, id);
            if (result)
            {
                TempData["Messages"] = "Successfully updated";
            }

            return RedirectToAction(nameof(Index));

        }

        [Authorize()]
        [HttpGet("Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleService.GetAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicle = await vehicleService.GetAsync(id);
            var model = new VehicleViewModel
            {
                IdentityNumber = vehicle.IdentityNumber,
                PlateNumber = vehicle.PlateNumber,
                CustomerName = vehicle.CustomerFullName,
            };
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await vehicleService.DeleteAsync(id);
            if (result)
            {
                TempData["Messages"] = "Successfully deleted";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("RefreshManufacturers")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RefreshManufacturers(int? id)
        {
            var manufacturers = await manufacturerService.GetAllAync();

            return Json(manufacturers);
        }

        [HttpGet("Manufacturermodels/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Manufacturermodels(int? id)
        {
            var models = await vehicleModelService.GetAllAsync();

            return Json(models.Where(x => x.ManufacturerId == id).Select(x => modelMapper.ToVehicleModelWithId(x)));
        }
      
        [HttpGet("ManModels")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Manufacturermodels(string name)
        {
            int manId;
            var incoming = int.TryParse(name, out manId);
            var models = await vehicleModelService.GetAllAsync();
            if (incoming)
            {
                return Json(models.Where(x => x.ManufacturerId == manId).Select(x => modelMapper.ToVehicleModelWithId(x)));
            }

            return Json(models.Where(x => x.Manufacturer == name).Select(x => modelMapper.ToVehicleModelWithId(x)));
        }
    }
}

SmartGarage/SmartGarage.Web/Views/Customers/ChangePassword.cshtml
@model SmartGarage.Services.Models.UserDTO

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container m-3">
    <h1>Change password</h1>
    @if (TempData["Messages"] != null)
    {
        if (@TempData["Messages"].ToString().Contains("Invalid"))
        {
            <div class="alert alert-danger" role="alert">
                <p>@TempData["Messages"]</p>
            </div>
        }
        else
        {
            <div class="alert alert-success" role="alert">
                <p>@TempData["Messages"]</p>
            </div>
        }

    }
    <div>
        <h4>User</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                New password
            </dt>
            <dd class="col-md-4">
                <form asp-action="ChangePassword" method="post">
                    <div class="form-group">
                        <input class="form-control" name="password" />
                        <input type="submit" value="Change" class="btn btn-primary mt-2" />
                        <a asp-controller="Visit" asp-action="Index">Back</a>
                    </div>
                </form>
            </dd>
        </dl>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Customers/Delete.cshtml
@model SmartGarage.Web.Models.CustomerViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Customer</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
        </dl>

        <form asp-action="Delete" method="post">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Customers/Details.cshtml
@model SmartGarage.Services.Models.UserDTO

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Messages"] != null)
{
    if (@TempData["Messages"].ToString().Contains("wrong"))
    {
        <div class="alert alert-danger" role="alert">
            <p>@TempData["Messages"]</p>
        </div>
    }
    else
    {
        <div class="alert alert-success" role="alert">
            <p>@TempData["Messages"]</p>
        </div>
    }

}
<style>
    tbody {
        flex: 1 1 auto;
        display: block;
        overflow-y: auto;
        overflow-x: hidden;
    }

    tr {
        width: 100%;
        display: table;
        table-layout: fixed;
    }
</style>
<div class="container mt-3">

    <div class="form-inline d-flex justify-content-md-between">
        <div>
            <h1>Details</h1>
            <h4>Customer</h4>
        </div>
        <div></div>
        <div>
            <form class="mb-2" method="get" asp-controller="Customers" asp-action="SendPdf" asp-route-id="@Model.Id">
                <input hidden name="customerId" value="@Model.Id" />
                <input type="submit" value="Send PDF" class="btn btn-outline-info" />
            </form>
            <form asp-controller="Customers" asp-action="SendResetPassowrd">
                <input hidden name="email" value="@Model.Email" />
                <input type="submit" value="Reset password" class="btn btn-outline-info" />
            </form>
        </div>
    </div>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Vehicles)
            </dt>
            <dd class="col-sm-6 m-2">
                <div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Make
                                </th>
                                <th>
                                    Model
                                </th>
                                <th>
                                    PlateNumber
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody style="height: 150px;overflow: scroll;">
                            @foreach (var item in Model.Vehicles)
                            {
                                <tr>
                                    <td>
                                        @item.Manufacturer
                                    </td>
                                    <td>
                                        @item.Model
                                    </td>
                                    <td>
                                        @item.PlateNumber
                                    </td>
                                    <td>
                                        <a asp-controller="Vehicles" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </dd>
        </dl>

    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Customers/Edit.cshtml
@model SmartGarage.Web.Models.CustomerViewModel
@using SmartGarage.Services.Extensions
@using SmartGarage.Data.Models.Enums
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery AntiForgery

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    <h1>Edit</h1>

    <h4>Customer</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">First Name</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Last Name</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label">Phone</label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Customers/Index.cshtml
@model SmartGarage.Services.Helpers.Pager<UserDTO>
@using SmartGarage.Services.Models;
@{
    ViewData["Title"] = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-3">
    <div class="text-center">
        <h1 class="display-4">Customers</h1>
        @if (TempData["Messages"] != null)
        {
            <div class="alert alert-success" role="alert">
                <p>@TempData["Messages"]</p>
            </div>
        }


        <div class="row mb-4 d-flex">
            <div class="col-md-12">
                <div class="form-inline d-flex justify-content-center">
                    <input class="form-control ml-3 mt-3" type="text" id="customerName" name="customerName" placeholder="Name" />
                    <input class="form-control ml-3 mt-3" type="tel" id="customerPhone" name="phone" placeholder="Phone" />
                    <input class="form-control ml-3 mt-3" type="email" id="customerEmail" name="email" placeholder="Email" />
                    <input class="form-control ml-3 mt-3" type="text" id="customerVehicle" name="vehicle" placeholder="Vehicle" />
                    <div class="row">
                        <input id="dateFrom" class="form-control input-sm ml-3 mt-3" name="from" type="date" textmode="Date" placeholder="Date From" />
                        - 
                        <input id="dateTo" class="form-control input-sm ml-3 mt-3" name="to" type="date" textmode="To" placeholder="Date To" />
                        <select id="dateFilter" class="form-control input-sm ml-3 mt-3">
                            <option value="true">Date In</option>
                            <option value="false">Date Out</option>
                        </select>
                        <button id="search" class="btn btn-primary ml-3 mt-3"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-inline d-flex justify-content-lg-start mb-2">
            <select class="form-control input-sm ml-3 mt-3" id="filterBy">
                <option value="def">--- Sort by ---</option>
                <option value="name">Name</option>
                <option value="date">Date</option>
            </select>
            <select class="form-control input-sm ml-3 mt-3" id="order">
                <option value="asc">Asc</option>
                <option value="desc">Desc</option>
            </select>
        </div>


        <div id="pagerCustomer">
            <partial name="_CustomersPartialViewPager" model="@Model" />
        </div>

    </div>
</div>

@section Scripts {
 <script src="~/js/CustomerIndex.js"></script>
}

SmartGarage/SmartGarage.Web/Views/Customers/SendPdf.cshtml
@model List<VisitDTO>
@using SmartGarage.Services.Models;
@{
    ViewData["Title"] = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-3">
    <h1 class="text-center">All visits</h1>
    <form asp-action="SendPdf">
        <div class="form-group">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Date
                        </th>
                        <th>
                            Vehicle
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {

                    <tr>
                        <td>
                            @Model[i].DateIn - @Model[i].DateOut
                        </td>
                        <td>
                            @Model[i].PlateNumber
                        </td>
                        <td>
                            @Model[i].TotalPrice
                        </td>
                        <td>

                            @Html.CheckBoxFor(x => x[i].ToSend)
                            <input asp-for="@Model[i].Id" value="@Model[i].Id" type="hidden" />
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <input type="submit" value="Send PDF" class="btn btn-outline-success" />
    </form>
</div>