SmartGarage/SmartGarage.Web/Models/AddVisitToCustomerViewModel.cs
using SmartGarage.Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Models
{
    public class AddVisitToCustomerViewModel
    {
        public string CustomerName { get; set; }
        public List<VehicleDTO> Vehicles { get; set; }
        public int VehicleId { get; set; }
        public List<ServiceDTO> Services { get; set; }
    }
}

SmartGarage/SmartGarage.Web/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using SmartGarage.Data.Models;
using SmartGarage.Services.Helpers;
using SmartGarage.Services.ModelMapper;
using SmartGarage.Services.Models;
using SmartGarage.Services.Models.CreateDTOs;
using SmartGarage.Services.Models.UpdateDTOs;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [Route("[controller]")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class CustomersController : Controller
    {
        private readonly IVehicleService vehicleService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleModelService vehicleModelService;
        private readonly IUserService userService;
        private readonly IModelMapper modelMapper;
        private readonly IVisitService visitService;
        private readonly UserManager<User> userManager;

        public CustomersController(IVehicleService vehicleService, IManufacturerService manufacturerService,
            IVehicleModelService vehicleModelService, IModelMapper modelMapper,
            IUserService userService, IVisitService visitService, UserManager<User> userManager)
        {
            this.vehicleService = vehicleService;
            this.manufacturerService = manufacturerService;
            this.vehicleModelService = vehicleModelService;
            this.modelMapper = modelMapper;
            this.userService = userService;
            this.visitService = visitService;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var pagerQueryObj = new PagerQueryObject(1, 0);

            var filterCustomers = new FilterUserQuery();

            var customers = await userService.GetAllCustomersAsync(filterCustomers, pagerQueryObj);

            return View(customers);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Details")]
        public async Task<IActionResult> Details(int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }
        [Authorize(Roles = "Employee")]
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await userService.GetCustomerAsync(id);

            var model = new CustomerViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email
            };

            if (user == null)
            {
                return NotFound();
            }

            return View(model);
        }
        [Authorize(Roles = "Employee")]
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await userService.DeleteAsync(id);

            if (result)
            {
                TempData["Messages"] = "Successfully deleted";
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await userService.GetCustomerAsync(id);
            var model = new CustomerViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Phone = user.Phone,
            };

            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Edit/{id}")]
        public async Task<IActionResult> Edit([Bind("FirstName,LastName,Email,Phone")] CustomerViewModel model, int id)
        {
            var userToUpdate = new UpdateUserDTO()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Phone = model.Phone,
            };

            var result = await userService.UpdateAsync(userToUpdate, id);
            if (result)
            {
                TempData["Messages"] = "Successfully updated";
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("PartialPager")]
        public async Task<IActionResult> PartialPager(string customerName, string email, string phone, string vehicle,
            DateTime from, DateTime to,string order,bool dateFilter,string filterBy, int pageNumber = 1)
        {

            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            var filterCustomers = new FilterUserQuery()
            {
                Name = customerName,
                Email = email,
                Phone = phone,
                Vehicle = vehicle,
                From = from,
                To = to,
                Order = order,
                DateFilter = dateFilter,
                SortBy = filterBy
                
            };

            var customers = await userService.GetAllCustomersAsync(filterCustomers, pagerQueryObj);

            return PartialView("_CustomersPartialViewPager",customers);
        }

        [HttpGet("ChangePassword/{id}")]
        public async Task<IActionResult> ChangePassword (int id)
        {
            var customer = await userService.GetUserAsync(id);

            return View(customer);
        }
        [HttpPost("ChangePassword/{id}")]
        public async Task<IActionResult> ChangePassword(int id,string password)
        {
            var result = await userService.ResetPassword(password,id);
            if (result)
            {
                TempData["Messages"] = "Successfully changed password";
            }
            else
            {
                TempData["Messages"] = "Invalid password";
            }
            var customer = await userService.GetUserAsync(id);
            return View(customer);
        }

        [HttpPost("SendResetPassowrd")]
        public async Task<IActionResult> SendResetPassowrd(string email)
        {
            var user = await userManager.FindByEmailAsync(email);
            if (email!=null)
            {
                var code = await userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                SendEmail.SendPassword(
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",email);
                TempData["Messages"] = "Successfully send link to email";
               return RedirectToAction("Details", new { id = user.Id });
            }
            TempData["Messages"] = "Something went wrong";
            return RedirectToAction("Details", new { id = user.Id });
        }

        [HttpGet("SendPdf/{id}")]
        public async Task<IActionResult> SendPdf(int id)
        {
            var visits = await visitService.GetAllAsync(id);
            return View(visits.ToList());
            
        }

        [HttpPost("SendPdf/{id}")]
        public async Task<IActionResult> SendPdf(List<VisitDTO> comingVisits,int id)
        {
            var customer = await userService.GetCustomerAsync(id);
            var visits = await visitService.GetAllAsync(id);
            var visitsToSend = comingVisits.Where(x => x.ToSend).Select(x => x.Id);
            await SendEmail.SendPdfAsync(visits.Where(x=> visitsToSend.Contains(x.Id)).ToList(),customer.Email);

            TempData["Messages"] = "Email sended";
            return RedirectToAction("Details", new { id = customer.Id });

        }
    }
}

SmartGarage/SmartGarage.Web/Views/Visit/AddVisitToCustomer.cshtml
@model SmartGarage.Web.Models.AddVisitToCustomerViewModel

@using SmartGarage.Services.Extensions

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    tbody {
        flex: 1 1 auto;
        display: block;
        overflow-y: auto;
        overflow-x: hidden;
    }

    tr {
        width: 100%;
        display: table;
        table-layout: fixed;
    }
</style>
<div class="container">
    <h1>Add</h1>

    <h4>Visit</h4>
    <hr />
    @if (TempData["Messages"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <p>@TempData["Messages"]</p>
        </div>
    }
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddVisitToCustomer">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input class="form-control" disabled value="@Model.CustomerName" />
                </div>
                <div class="form-group">
                    <label asp-for="VehicleId" class="control-label">Vehicle</label>
                    <select asp-for="VehicleId" class="form-control select2" asp-items="Model.Vehicles.ToSelectListItem()"></select>
                    <span asp-validation-for="VehicleId" class="text-danger" id="makeSpan"></span>
                </div>
                <h5>Services</h5>
                <hr />
                <div class="form-group">
                    <table class="table w-100">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th class="text-center">
                                    <i class="far fa-check-square"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody style="height: 250px;overflow: scroll;">
                            @for (int i = 0; i < Model.Services.Count; i++)
                            {

                                <tr>
                                    <td>
                                        @Model.Services[i].Name
                                    </td>
                                    <td>
                                        @Model.Services[i].Price
                                    </td>
                                    <td class="text-center">

                                        @Html.CheckBoxFor(x => x.Services[i].AddToVisit)
                                        <input asp-for="Services[i].Id" value="@Model.Services[i].Id" type="hidden" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add Visit" class="btn btn-primary" />
                </div>
                <a asp-controller="Customers" asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Visit/CheckOut.cshtml
@model SmartGarage.Services.Models.VisitDTO
@using SmartGarage.Data.Models.Enums
@{
    ViewData["Title"] = "CheckOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    @if (TempData["Messages"] != null)
    {

        <div class="alert alert-danger" role="alert">
            <p>@TempData["Messages"]</p>
        </div>
    }
    <h1>Check out</h1>

    <h3>Are you sure you want to check out?</h3>
    <div>
        <h4>Visit</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CustomerName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CustomerName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PlateNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PlateNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.VehicleModel)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.VehicleModel)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StatusName)
            </dd>
        </dl>

        <form asp-route-id="@Model.Id" asp-action="CheckOut" method="post">
            <input type="submit" value="Check out" class="btn btn-outline-warning" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Visit/Create.cshtml
@model SmartGarage.Web.Models.CreateVisitNotRegisterdCustomer
@using SmartGarage.Services.Models
@using SmartGarage.Services.Extensions
@using SmartGarage.Data.Models.Enums
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery AntiForgery

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    tbody {
        flex: 1 1 auto;
        display: block;
        overflow-y: auto;
        overflow-x: hidden;
    }

    tr {
        width: 100%;
        display: table;
        table-layout: fixed;
    }
</style>

<div class="container">

    <h1>Create</h1>

    <h4>Visit</h4>
    <hr />
    @if (TempData["Messages"] != null)
    {

        <div class="alert alert-danger" role="alert">
            <p>@TempData["Messages"]</p>
        </div>
    }
    <form asp-action="Create">

        <div class="row">
            <div class="col-md-6">
                <h5>Customer</h5>
                <hr />
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">First Name</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Last Name</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label">Phone</label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <hr />
                <h5>Services</h5>
                <div class="form-group">
                    <table class="table w-100">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th class="text-center">
                                    <i class="far fa-check-square"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody style="height: 250px;overflow: scroll;">
                            @for (int i = 0; i < Model.Services.Count; i++)
                            {

                                <tr>
                                    <td>
                                        @Model.Services[i].Name
                                    </td>
                                    <td>
                                        @Model.Services[i].Price
                                    </td>
                                    <td class="text-center">

                                        @Html.CheckBoxFor(x => x.Services[i].AddToVisit)
                                        <input asp-for="Services[i].Id" value="@Model.Services[i].Id" type="hidden" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-6">
                <h5>Vehicle</h5>
                <hr />
                <div class="form-group">
                    <label asp-for="PlateNumber" class="control-label">Plate Number</label>
                    <input asp-for="PlateNumber" class="form-control" />
                    <span asp-validation-for="PlateNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IdentityNumber" class="control-label">Identity Number</label>
                    <input asp-for="IdentityNumber" class="form-control" />
                    <span asp-validation-for="IdentityNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label">Type</label>
                    <select asp-for="Type" class="form-control select2" asp-items="Html.GetEnumSelectList<VehicleTypes>()"></select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ManufacturerId" class="control-label">Manufacturer</label>
                    <select asp-for="ManufacturerId" class="form-control select2" asp-items="Model.Manufacturers.ToSelectListItem()" id="Make"></select>
                    <span asp-validation-for="ManufacturerId" class="text-danger"></span>
                    <a href="#" class="btn-link" id="newMake">Add new</a>
                </div>
                <div class="form-group">
                    <label asp-for="VehicleModelId" class="control-label">Model</label>
                    <select asp-for="VehicleModelId" class="form-control select2" asp-items="Model.Models.ToSelectListItem()" id="Model"></select>
                    <span asp-validation-for="VehicleModelId" class="text-danger"></span>
                    <a href="#" class="btn-link" id="newModel">Add new</a>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index">Back to List</a>
            </div>

        </div>
    </form>
    <div class="modal" tabindex="-1" role="dialog" id="form-modal-make">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button id="makeClose" type="submit" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </div>
                <div class="modal-body p-0 w-100">
                    <partial name="_CreatePopUpPartial" model="new ManufacturerDTO()" />
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="form-modal-model">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button id="modelClose" type="submit" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </div>
                <div class="modal-body p-0 w-100">
                    <partial name="_CreatePopUpModel" model="new VehicleModelDTO()" />
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>

    $(document).ready(function () {
            var MakeDDL = $("#Make");
            var ModelDDL = $("#Model");
            ModelDDL.prop('disabled', true);

            MakeDDL.change(function () {
                if ($(this).val() == "0") {
                    ModelDDL.prop('disabled', true);
                    ModelDDL.val("0");
                }
                else {
                    $.ajax({
                        url: '/Vehicles/Manufacturermodels/' + $(this).val(),
                        method: "get",
                        headers: {
                            'RequestVerificationToken': '@AntiForgery.GetAndStoreTokens(Context).RequestToken'
                        },
                        success: function (data) {
                            ModelDDL.prop('disabled', false);
                            ModelDDL.empty();
                            ModelDDL.append($('<option/>', { value: '0', text: '--Select Model--' }));
                            $(data).each(function (index, item) {
                                ModelDDL.append($('<option/>', { value: item.id, text: item.name }));
                            });
                        }
                    });
                }
            });

        });

        $(document).on("click", "#newMake",
            function (res) {
                $("#form-modal-make").modal();
            });


        $(document).ready(function () {
            $('#newModel').hide();
            $('#Make').change(function () {
                if ($('#Make').val() == "0") {

                    $('#newModel').hide();
                }
                else {
                    $('#newModel').show();
                    $(document).on("click", "#newModel",
                        function (res) {
                            $("#form-modal-model").modal();
                        });
                }
            });
        });

        $(document).on("click", "#createButton", function () {
            var val = $('#name').val();
            $.ajax({
                url: "/Manufacturers/CreatePopUp",
                type: "GET",
                data: { name: val }
            })
                .done(function (partialViewForMessage) {
                    $("#messgePartial").html(partialViewForMessage);
                });
        });

        $(document).on("click", "#createModelButton", function () {
            var val = $('#Modelname').val();
            $.ajax({
                url: "/Models/CreatePoPModel",
                type: "GET",
                data: { name: val, manName: $("#Make").val() }
            })
                .done(function (partialViewForMessage) {
                    $("#messgePartialModel").html(partialViewForMessage);
                });
        });

        $(document).on("click", "#makeClose", function () {
                $.ajax({
                    url: "/Vehicles/RefreshManufacturers",
                    type: "GET",
                    headers: {
                        'RequestVerificationToken': '@AntiForgery.GetAndStoreTokens(Context).RequestToken'
                    },
                    success: function (data) {
                        $("#Make").empty();
                        $("#Make").append($('<option/>', { value: '0', text: '--Select Model--' }));
                        $(data).each(function (index, item) {
                            $("#Make").append($('<option/>', { value: item.id, text: item.name }));
                        });
                    }
                });
            });

        $(document).on("click", "#modelClose", function () {
                $.ajax({
                    url: "/Vehicles/ManModels",
                    method: "GET",
                    data: { name: $("#Make").val() },
                        headers: {
                            'RequestVerificationToken': '@AntiForgery.GetAndStoreTokens(Context).RequestToken'
                        },
                        success: function (data) {
                            $("#Model").prop('disabled', false);
                            $("#Model").empty();
                            $("#Model").append($('<option/>', { value: '0', text: '--Select Model--' }));
                            $(data).each(function (index, item) {
                                $("#Model").append($('<option/>', { value: item.id, text: item.name }));
                            });
                        }
                    });
            });

</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('.select2').select2();
    </script>
}

SmartGarage/SmartGarage.Web/Views/Visit/Details.cshtml
@model SmartGarage.Services.Models.VisitDTO
@using SmartGarage.Data.Models.Enums

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-3">
    <div id="pdfContainer">
            <h1>Details</h1>
            <h4>Visit</h4>
        <div>
            <hr />

            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CustomerName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CustomerName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.VehicleMake)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.VehicleMake)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.VehicleModel)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.VehicleModel)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.PlateNumber)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PlateNumber)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.StatusName)
                </dd>
                <dt class="col-sm-2">
                    Date
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DateIn) -  @Html.DisplayFor(model => model.DateOut)
                </dd>
                <dt class="col-sm-2 mt-1 mb-1">
                    @Html.DisplayNameFor(model => model.Services)
                </dt>
                <dd class="col-sm-10 mt-1 mb-1">
                    <div id="currencyExchange">
                        <partial name="_VisitDetailsPartial" model="@Model" />
                    </div>
                </dd>
            </dl>
        </div>

    </div>
    <div>
        <a onclick="downloadPdf()" href="#" class="btn btn-success">Download Pdf</a> |
        @if (User.IsInRole("Employee"))
        {
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit |</a> 
        }
    <a asp-action="Index">Back to List</a>
    <div class="form-inline d-flex justify-content-lg-start mb-2">
        <h5 class="m-0 pt-2">Currency</h5>
        <select class="form-control input-sm ml-3 mt-3" id="currency">
            <option>EUR</option>
            <option>USD</option>
            <option>BGN</option>
        </select>
    </div>
    </div>
</div>
<input id="visitId" hidden value="@Model.Id"/>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/VisitDetails.js"></script>
}

SmartGarage/SmartGarage.Web/Views/Visit/Edit.cshtml
@model SmartGarage.Services.Models.VisitDTO
@using SmartGarage.Data.Models.Enums
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

    <h1>Edit</h1>
    <h4>Visit</h4>
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Edit">
                <div class="form-group">
                    <label asp-for="Status" class="control-label">Status</label>
                    <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<Status>()"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>