SmartGarage/SmartGarage.Web/Controllers/ManufacturersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.Data.Models;
using SmartGarage.Services.Models;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [Route("[controller]")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ManufacturersController : Controller
    {
        private readonly IVehicleModelService vehicleModelService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleService vehicleService;
        private readonly UserManager<User> userManager;
        public ManufacturersController(IManufacturerService manufacturerService, UserManager<User> userManager, IVehicleModelService vehicleModelService, IVehicleService vehicleService)
        {
            this.manufacturerService = manufacturerService;
            this.userManager = userManager;
            this.vehicleModelService = vehicleModelService;
            this.vehicleService = vehicleService;
        }
        [Authorize(Roles = "Employee")]
        [HttpGet]
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            return View(await manufacturerService.GetAllAync(pagerQueryObj));
        }
        [Authorize(Roles = "Employee")]
        [HttpGet("Restore")]
        public async Task<IActionResult> IndexDeleted(int pageNumber = 1)
        {
            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            return View(await manufacturerService.GetAllDeletedAync(pagerQueryObj));
        }

       
        [Authorize(Roles = "Employee")]
        [HttpGet("CreatePopUp")]
        public async Task<IActionResult> CreatePopUp(string name)
        {
            var model = new ManufacturerDTO()
            {
                Name = name
            };

            if (name != null)
            {
                try
                {
                    await manufacturerService.CreateAync(model);
                    //TempData["Messages"] = "Successfully created new vehicle manufacturer";                
                    return PartialView("_MessagePartial", new MessagePartial { Message = "Successfully created new vehicle manufacturer", GoodOrBad = true });
                }
                catch
                {

                    return PartialView("_MessagePartial", new MessagePartial { Message = "Manufacturer already exists", GoodOrBad = false });
                }    
                
            }
            return PartialView("_MessagePartial", new MessagePartial { Message = "You need to enter valid name", GoodOrBad = false });
        }


        [Authorize(Roles = "Employee")]
        [HttpGet("Create")]
        public async Task<IActionResult> Create()
        {
            ViewData["Id"] = new SelectList(await this.manufacturerService.GetAllAync(), "Name");
            return View();
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Create")]
        public async Task<IActionResult> Create([Bind("Name")] ManufacturerDTO model)
        {
            if (ModelState.IsValid)
            {
                await manufacturerService.CreateAync(model);
                TempData["Messages"] = "Successfully created new vehicle manufacturer";
                return RedirectToAction("Index", "Manufacturers");
            }
            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var manufacturer = await manufacturerService.GetAync(id);
            var model = new ManufacturerDTO
            {
                Name = manufacturer.Name,
            };
            if (manufacturer == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await manufacturerService.DeleteAsync(id);
            if (result)
            {
                TempData["Messages"] = "Successfully deleted";
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Restore/{id}")]
        public async Task<IActionResult> Restore(int id)
        {
            var manufacturer = await manufacturerService.GetAync(id);
            var model = new ManufacturerDTO
            {
                Name = manufacturer.Name,
            };
            if (manufacturer == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Restore/{id}"), ActionName("Restore")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RestoreConfirmed(int id)
        {
            var result = await manufacturerService.RestoreAsync(id);
            if (result)
            {
                TempData["Messages"] = "Successfully restored";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

SmartGarage/SmartGarage.Web/Controllers/ModelsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.Data.Models;
using SmartGarage.Services.Models;
using SmartGarage.Services.QueryObject;
using SmartGarage.Services.Services.Interfaces;
using SmartGarage.Web.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.Web.Controllers
{
    [Authorize()]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("[controller]")]
    public class ModelsController : Controller
    {
        private readonly IVehicleModelService vehicleModelService;
        private readonly IManufacturerService manufacturerService;
        private readonly IVehicleService vehicleService;
        private readonly UserManager<User> userManager;
        public ModelsController(IVehicleModelService vehicleModelService,
                                        IManufacturerService manufacturerService,
                                        UserManager<User> userManager,
                                        IVehicleService vehicleService)
        {
            this.vehicleModelService = vehicleModelService;
            this.manufacturerService = manufacturerService;
            this.userManager = userManager;
            this.vehicleService = vehicleService;
        }

        [Authorize(Roles = "Employee")]
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int id, int pageNumber = 1)
        {
            var pagerQueryObj = new PagerQueryObject(pageNumber, 0);

            var input = await manufacturerService.GetAync(id);

            var models = await vehicleModelService.GetAllAsync(input.Name, pagerQueryObj);

            return View(models);
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("Create/{id}")]
        public async Task<IActionResult> Create(int id)
        {
            var manufacturer = await manufacturerService.GetAync(id);

            var model = new ModelsViewModel()
            {
                ManufacturerId = manufacturer.Id,
                Manufacturer = manufacturer.Name
            };

            return View(model);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost("Create/{id}")]
        public async Task<IActionResult> Create(ModelsViewModel model, int id)
        {
            if (model == null)
            {
                model = new ModelsViewModel();
            };
            var modelToCreate = new VehicleModelDTO
            {
                ManufacturerId = id,
                Manufacturer = model.Manufacturer,
                Name = model.Name
            };
            if (ModelState.IsValid)
            {
                await vehicleModelService.CreateAsync(modelToCreate);
                TempData["Messages"] = "Successfully created new vehicle model";
                return RedirectToAction("Index", new { id = id });
            }
            return View(modelToCreate);
        }


        [Authorize(Roles = "Employee")]
        [HttpGet("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicleModel = await vehicleModelService.GetAsync(id);
            var model = new ModelsViewModel
            {
                Name = vehicleModel.Name,
                Manufacturer = vehicleModel.Manufacturer
            };

            if (vehicleModel == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost("Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicleToDelete = await vehicleModelService.GetAsync(id);
            var vehicleToDeleteManufacturerId = vehicleToDelete.ManufacturerId;

            var result = await vehicleModelService.DeleteAsync(id);
            if (result)
            {
                TempData["Messages"] = "Successfully deleted";
            }
            return RedirectToAction("Index", new { id = vehicleToDeleteManufacturerId });
        }

        [Authorize(Roles = "Employee")]
        [HttpGet("CreatePoPModel")]
        public async Task<IActionResult> CreatePoPModel(string name, string manName)
        {
            int manId;
            var incoming = int.TryParse(manName,out manId);
            if (name == null)
            {
                return PartialView("_MessagePartial", new MessagePartial { Message = "You need to enter valid name", GoodOrBad = false });
            }
            if (!incoming)
            {

                var mans = await manufacturerService.GetAllAync();
                var id = mans.FirstOrDefault(x => x.Name == manName).Id;

                var modelToCreate = new VehicleModelDTO
                {
                    ManufacturerId = id,
                    Name = name
                };
                if (vehicleModelService.GetAllAsync().Result.Where(x => x.ManufacturerId == id).Select(x => x.Name).Contains(name))
                {
                    return PartialView("_MessagePartial", new MessagePartial { Message = "Model already exists for this manufacturer", GoodOrBad = false });
                }

                await vehicleModelService.CreateAsync(modelToCreate);
                return PartialView("_MessagePartial", new MessagePartial { Message = "Successfully created new vehicle model", GoodOrBad = true });
            }
            else
            {
            
                var modelToCreate = new VehicleModelDTO
                {
                    ManufacturerId = manId,
                    Name = name
                };
                var res = await vehicleModelService.GetAllAsync();
                if (res.Where(x => x.ManufacturerId == manId).Select(x => x.Name).Contains(name))
                {
                    return PartialView("_MessagePartial", new MessagePartial { Message = "Model already exists for this manufacturer", GoodOrBad = false });
                }

                await vehicleModelService.CreateAsync(modelToCreate);
                return PartialView("_MessagePartial", new MessagePartial { Message = "Successfully created new vehicle model", GoodOrBad = true });

            }


        }
    }
}

SmartGarage/SmartGarage.Web/Views/Manufacturers/Create.cshtml
@model SmartGarage.Services.Models.ManufacturerDTO
@using SmartGarage.Web.Models
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery AntiForgery
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    <h1>Create</h1>

    <h4>Manufacturer</h4>
    <hr />
    <div class="row">
        <div class="col-12">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">Manufacturer</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

SmartGarage/SmartGarage.Web/Views/Manufacturers/Delete.cshtml
@model SmartGarage.Services.Models.ManufacturerDTO

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Manufacturer</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="Delete" method="post">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Manufacturers/Index.cshtml
@model SmartGarage.Services.Helpers.Pager<ManufacturerDTO>
@using SmartGarage.Services.Models;
@using SmartGarage.Data.Models.Enums
@{
    ViewData["Title"] = "Manufacturers";
}

<div class="container mt-3">
    <div class="text-center">
        <h1 class="display-4">Manufacturers</h1>
        @if (TempData["Messages"] != null)
        {
            <div class="alert alert-success" role="alert">
                <p>@TempData["Messages"]</p>
            </div>
        }
        <p>
            <a asp-action="Create" class="btn btn-success" title="Create new"><i class="far fa-plus-square"></i></a>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Options
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(i => item.Name)
                        </td>
                        <td>
                            @if (User.IsInRole("Employee"))
                            {
                            <a asp-controller="Models" asp-action="Create" asp-route-id="@item.Id" class="btn btn-success" title="Add model"><i class="fas fa-folder-plus"></i></a>
                            }
                            @if (User.IsInRole("Employee"))
                            {
                                <a asp-controller="Models" asp-action="Index" asp-route-id="@item.Id" class="btn btn-outline-info" title="Available Models"><i class="fas fa-list"></i></a>
                            }
                            @if (User.IsInRole("Employee"))
                            {
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Delete"><i class="far fa-trash-alt"></i></a>
                            }
                        </td>

                    </tr>
                }
            </tbody>
        </table>
        <p>
            <a asp-action="IndexDeleted" class="btn btn-outline-info" title="Restore Deleted Manufacturer"> <i class="fas fa-external-link-square-alt"></i></a>
        </p>
        @{
            var prevDisabled = !Model.PrevPage ? "disabled" : "";
            var nextDisabled = !Model.NextPage ? "disabled" : "";
        }
        <a asp-action="Index" asp-route-pageNumber="@(Model.Page - 1)" class="btn btn-default @prevDisabled">
            Previous
        </a>
        @Model.Page / @Model.TotalPages
        <a asp-action="Index" asp-route-pageNumber="@(Model.Page + 1)" class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Manufacturers/IndexDeleted.cshtml
@model SmartGarage.Services.Helpers.Pager<ManufacturerDTO>
@using SmartGarage.Services.Models;
@using SmartGarage.Data.Models.Enums
@{
    ViewData["Title"] = "Manufacturers";
}

<div class="container mt-3">
    <div class="text-center">
        <h1 class="display-4">Manufacturers</h1>
        @if (TempData["Messages"] != null)
        {
            <div class="alert alert-success" role="alert">
                <p>@TempData["Messages"]</p>
            </div>
        }

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Restore Manufacturer
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(i => item.Name)
                        </td>
                        <td>
                            @if (User.IsInRole("Employee"))
                            {
                            <a asp-action="Restore" asp-route-id="@item.Id" class="btn btn-outline-info" title="Restore Deleted Manufacturer"> <i class="fas fa-external-link-square-alt"></i></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-controller="Manufacturers" asp-action="Index" class="btn btn-outline-success" title="Back to Manufacturers"><i class="fas fa-external-link-square-alt"></i></a>
        @{
            var prevDisabled = !Model.PrevPage ? "disabled" : "";
            var nextDisabled = !Model.NextPage ? "disabled" : "";
        }
        <a asp-action="Index" asp-route-pageNumber="@(Model.Page - 1)" class="btn btn-default @prevDisabled">
            Previous
        </a>
        @Model.Page / @Model.TotalPages
        <a asp-action="Index" asp-route-pageNumber="@(Model.Page + 1)" class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
</div>

SmartGarage/SmartGarage.Web/Views/Manufacturers/Restore.cshtml
@model SmartGarage.Services.Models.ManufacturerDTO

@{
    ViewData["Title"] = "Restore";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-3">
    <h1>Restore</h1>

    <h3>Are you sure you want to restore this?</h3>
    <div>
        <h4>Manufacturer</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="Restore" method="post">
            <input type="submit" value="Restore" class="btn btn-outline-primary" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>